name: mybook_library
description: A personal book library management app.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  open_file: ^3.3.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/image/